export const LOCAL_STORAGE_AK_NAME = "AK";
export const LOCAL_STORAGE_SK_NAME = "SK";
export const LOCAL_STORAGE_ENDPOINT_NAME = "ENDPOINT";
export const LOCAL_STORAGE_BEDROCK_API_KEY_NAME = "BEDROCK_API_KEY";
export const FRONTEND_NAME = "MultiLLM Gateway";
